name: Deploy to Azure App Service

on:
  push:
    branches:
      - main  # Change to the branch you want to trigger deployments from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        az --version

    - name: Login to Azure
      run: |
        az login --service-principal -u ${{ secrets.AZURE_SP_APP_ID }} -p ${{ secrets.AZURE_SP_PASSWORD }} --tenant ${{ secrets.AZURE_SP_TENANT_ID }}
        az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Build and deploy HTML files
      run: |
        # Change this to the directory containing your HTML files
        cd index.html

        # Use Azure CLI to deploy HTML files to Azure App Service
        az webapp up --name Shin-Era-Tech --resource-group Shin-Era-Tech

    - name: Clean up
      run: |
        az logout

